apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-and-sidecar
  name: python-and-sidecar
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-and-sidecar
    deploymentconfig: python-and-sidecar
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
